version: "2"
services:
  web:
    build: ./web
    container_name: web
    ports:
      - "127.0.0.1:80:3000"
    volumes:
      - "./web:/data/docroot"
  app:
    build: ./app
    container_name: app
    ports:
      - "3030:3030"
    volumes:
      - "./app:/data/docroot"
